// Code generated by protoc-gen-go.
// source: a.proto
// DO NOT EDIT!

/*
Package Econix is a generated protocol buffer package.

It is generated from these files:
	a.proto

It has these top-level messages:
	Transaction
*/
package Econix

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Transaction_ItemType int32

const (
	Transaction_TypeX Transaction_ItemType = 0
	Transaction_TypeY Transaction_ItemType = 1
	Transaction_TypeZ Transaction_ItemType = 2
	Transaction_TypeA Transaction_ItemType = 3
)

var Transaction_ItemType_name = map[int32]string{
	0: "TypeX",
	1: "TypeY",
	2: "TypeZ",
	3: "TypeA",
}
var Transaction_ItemType_value = map[string]int32{
	"TypeX": 0,
	"TypeY": 1,
	"TypeZ": 2,
	"TypeA": 3,
}

func (x Transaction_ItemType) Enum() *Transaction_ItemType {
	p := new(Transaction_ItemType)
	*p = x
	return p
}
func (x Transaction_ItemType) String() string {
	return proto.EnumName(Transaction_ItemType_name, int32(x))
}
func (x *Transaction_ItemType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Transaction_ItemType_value, data, "Transaction_ItemType")
	if err != nil {
		return err
	}
	*x = Transaction_ItemType(value)
	return nil
}

type Transaction struct {
	ClientName       *string                `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	ClientId         *int32                 `protobuf:"varint,2,req,name=clientId" json:"clientId,omitempty"`
	Description      *string                `protobuf:"bytes,3,opt,name=description,def=NONE" json:"description,omitempty"`
	Messageitems     []*Transaction_MsgItem `protobuf:"bytes,4,rep,name=messageitems" json:"messageitems,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}

const Default_Transaction_Description string = "NONE"

func (m *Transaction) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *Transaction) GetClientId() int32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *Transaction) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return Default_Transaction_Description
}

func (m *Transaction) GetMessageitems() []*Transaction_MsgItem {
	if m != nil {
		return m.Messageitems
	}
	return nil
}

type Transaction_MsgItem struct {
	Id               *int32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ItemName         *string               `protobuf:"bytes,2,opt,name=itemName" json:"itemName,omitempty"`
	ItemValue        *int32                `protobuf:"varint,3,opt,name=itemValue" json:"itemValue,omitempty"`
	ItemType         *Transaction_ItemType `protobuf:"varint,4,opt,name=itemType,enum=Econix.Transaction_ItemType" json:"itemType,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Transaction_MsgItem) Reset()         { *m = Transaction_MsgItem{} }
func (m *Transaction_MsgItem) String() string { return proto.CompactTextString(m) }
func (*Transaction_MsgItem) ProtoMessage()    {}

func (m *Transaction_MsgItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Transaction_MsgItem) GetItemName() string {
	if m != nil && m.ItemName != nil {
		return *m.ItemName
	}
	return ""
}

func (m *Transaction_MsgItem) GetItemValue() int32 {
	if m != nil && m.ItemValue != nil {
		return *m.ItemValue
	}
	return 0
}

func (m *Transaction_MsgItem) GetItemType() Transaction_ItemType {
	if m != nil && m.ItemType != nil {
		return *m.ItemType
	}
	return Transaction_TypeX
}

func init() {
	proto.RegisterEnum("Econix.Transaction_ItemType", Transaction_ItemType_name, Transaction_ItemType_value)
}
