// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a.proto

#ifndef PROTOBUF_a_2eproto__INCLUDED
#define PROTOBUF_a_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Econix {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_a_2eproto();
void protobuf_AssignDesc_a_2eproto();
void protobuf_ShutdownFile_a_2eproto();

class Transaction;
class Transaction_MsgItem;

enum Transaction_ItemType {
  Transaction_ItemType_TypeX = 0,
  Transaction_ItemType_TypeY = 1,
  Transaction_ItemType_TypeZ = 2,
  Transaction_ItemType_TypeA = 3
};
bool Transaction_ItemType_IsValid(int value);
const Transaction_ItemType Transaction_ItemType_ItemType_MIN = Transaction_ItemType_TypeX;
const Transaction_ItemType Transaction_ItemType_ItemType_MAX = Transaction_ItemType_TypeA;
const int Transaction_ItemType_ItemType_ARRAYSIZE = Transaction_ItemType_ItemType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Transaction_ItemType_descriptor();
inline const ::std::string& Transaction_ItemType_Name(Transaction_ItemType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Transaction_ItemType_descriptor(), value);
}
inline bool Transaction_ItemType_Parse(
    const ::std::string& name, Transaction_ItemType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Transaction_ItemType>(
    Transaction_ItemType_descriptor(), name, value);
}
// ===================================================================

class Transaction_MsgItem : public ::google::protobuf::Message {
 public:
  Transaction_MsgItem();
  virtual ~Transaction_MsgItem();

  Transaction_MsgItem(const Transaction_MsgItem& from);

  inline Transaction_MsgItem& operator=(const Transaction_MsgItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Transaction_MsgItem& default_instance();

  void Swap(Transaction_MsgItem* other);

  // implements Message ----------------------------------------------

  Transaction_MsgItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Transaction_MsgItem& from);
  void MergeFrom(const Transaction_MsgItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string itemName = 2;
  inline bool has_itemname() const;
  inline void clear_itemname();
  static const int kItemNameFieldNumber = 2;
  inline const ::std::string& itemname() const;
  inline void set_itemname(const ::std::string& value);
  inline void set_itemname(const char* value);
  inline void set_itemname(const char* value, size_t size);
  inline ::std::string* mutable_itemname();
  inline ::std::string* release_itemname();
  inline void set_allocated_itemname(::std::string* itemname);

  // optional int32 itemValue = 3;
  inline bool has_itemvalue() const;
  inline void clear_itemvalue();
  static const int kItemValueFieldNumber = 3;
  inline ::google::protobuf::int32 itemvalue() const;
  inline void set_itemvalue(::google::protobuf::int32 value);

  // optional .Econix.Transaction.ItemType itemType = 4;
  inline bool has_itemtype() const;
  inline void clear_itemtype();
  static const int kItemTypeFieldNumber = 4;
  inline ::Econix::Transaction_ItemType itemtype() const;
  inline void set_itemtype(::Econix::Transaction_ItemType value);

  // @@protoc_insertion_point(class_scope:Econix.Transaction.MsgItem)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_itemname();
  inline void clear_has_itemname();
  inline void set_has_itemvalue();
  inline void clear_has_itemvalue();
  inline void set_has_itemtype();
  inline void clear_has_itemtype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* itemname_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 itemvalue_;
  int itemtype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_a_2eproto();
  friend void protobuf_AssignDesc_a_2eproto();
  friend void protobuf_ShutdownFile_a_2eproto();

  void InitAsDefaultInstance();
  static Transaction_MsgItem* default_instance_;
};
// -------------------------------------------------------------------

class Transaction : public ::google::protobuf::Message {
 public:
  Transaction();
  virtual ~Transaction();

  Transaction(const Transaction& from);

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Transaction& default_instance();

  void Swap(Transaction* other);

  // implements Message ----------------------------------------------

  Transaction* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Transaction& from);
  void MergeFrom(const Transaction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Transaction_MsgItem MsgItem;

  typedef Transaction_ItemType ItemType;
  static const ItemType TypeX = Transaction_ItemType_TypeX;
  static const ItemType TypeY = Transaction_ItemType_TypeY;
  static const ItemType TypeZ = Transaction_ItemType_TypeZ;
  static const ItemType TypeA = Transaction_ItemType_TypeA;
  static inline bool ItemType_IsValid(int value) {
    return Transaction_ItemType_IsValid(value);
  }
  static const ItemType ItemType_MIN =
    Transaction_ItemType_ItemType_MIN;
  static const ItemType ItemType_MAX =
    Transaction_ItemType_ItemType_MAX;
  static const int ItemType_ARRAYSIZE =
    Transaction_ItemType_ItemType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ItemType_descriptor() {
    return Transaction_ItemType_descriptor();
  }
  static inline const ::std::string& ItemType_Name(ItemType value) {
    return Transaction_ItemType_Name(value);
  }
  static inline bool ItemType_Parse(const ::std::string& name,
      ItemType* value) {
    return Transaction_ItemType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string clientName = 1;
  inline bool has_clientname() const;
  inline void clear_clientname();
  static const int kClientNameFieldNumber = 1;
  inline const ::std::string& clientname() const;
  inline void set_clientname(const ::std::string& value);
  inline void set_clientname(const char* value);
  inline void set_clientname(const char* value, size_t size);
  inline ::std::string* mutable_clientname();
  inline ::std::string* release_clientname();
  inline void set_allocated_clientname(::std::string* clientname);

  // required int32 clientId = 2;
  inline bool has_clientid() const;
  inline void clear_clientid();
  static const int kClientIdFieldNumber = 2;
  inline ::google::protobuf::int32 clientid() const;
  inline void set_clientid(::google::protobuf::int32 value);

  // optional string description = 3 [default = "NONE"];
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 3;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  inline void set_allocated_description(::std::string* description);

  // repeated .Econix.Transaction.MsgItem messageitems = 4;
  inline int messageitems_size() const;
  inline void clear_messageitems();
  static const int kMessageitemsFieldNumber = 4;
  inline const ::Econix::Transaction_MsgItem& messageitems(int index) const;
  inline ::Econix::Transaction_MsgItem* mutable_messageitems(int index);
  inline ::Econix::Transaction_MsgItem* add_messageitems();
  inline const ::google::protobuf::RepeatedPtrField< ::Econix::Transaction_MsgItem >&
      messageitems() const;
  inline ::google::protobuf::RepeatedPtrField< ::Econix::Transaction_MsgItem >*
      mutable_messageitems();

  // @@protoc_insertion_point(class_scope:Econix.Transaction)
 private:
  inline void set_has_clientname();
  inline void clear_has_clientname();
  inline void set_has_clientid();
  inline void clear_has_clientid();
  inline void set_has_description();
  inline void clear_has_description();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* clientname_;
  ::std::string* description_;
  static ::std::string* _default_description_;
  ::google::protobuf::RepeatedPtrField< ::Econix::Transaction_MsgItem > messageitems_;
  ::google::protobuf::int32 clientid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_a_2eproto();
  friend void protobuf_AssignDesc_a_2eproto();
  friend void protobuf_ShutdownFile_a_2eproto();

  void InitAsDefaultInstance();
  static Transaction* default_instance_;
};
// ===================================================================


// ===================================================================

// Transaction_MsgItem

// required int32 id = 1;
inline bool Transaction_MsgItem::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Transaction_MsgItem::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Transaction_MsgItem::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Transaction_MsgItem::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Transaction_MsgItem::id() const {
  return id_;
}
inline void Transaction_MsgItem::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional string itemName = 2;
inline bool Transaction_MsgItem::has_itemname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Transaction_MsgItem::set_has_itemname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Transaction_MsgItem::clear_has_itemname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Transaction_MsgItem::clear_itemname() {
  if (itemname_ != &::google::protobuf::internal::kEmptyString) {
    itemname_->clear();
  }
  clear_has_itemname();
}
inline const ::std::string& Transaction_MsgItem::itemname() const {
  return *itemname_;
}
inline void Transaction_MsgItem::set_itemname(const ::std::string& value) {
  set_has_itemname();
  if (itemname_ == &::google::protobuf::internal::kEmptyString) {
    itemname_ = new ::std::string;
  }
  itemname_->assign(value);
}
inline void Transaction_MsgItem::set_itemname(const char* value) {
  set_has_itemname();
  if (itemname_ == &::google::protobuf::internal::kEmptyString) {
    itemname_ = new ::std::string;
  }
  itemname_->assign(value);
}
inline void Transaction_MsgItem::set_itemname(const char* value, size_t size) {
  set_has_itemname();
  if (itemname_ == &::google::protobuf::internal::kEmptyString) {
    itemname_ = new ::std::string;
  }
  itemname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Transaction_MsgItem::mutable_itemname() {
  set_has_itemname();
  if (itemname_ == &::google::protobuf::internal::kEmptyString) {
    itemname_ = new ::std::string;
  }
  return itemname_;
}
inline ::std::string* Transaction_MsgItem::release_itemname() {
  clear_has_itemname();
  if (itemname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = itemname_;
    itemname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Transaction_MsgItem::set_allocated_itemname(::std::string* itemname) {
  if (itemname_ != &::google::protobuf::internal::kEmptyString) {
    delete itemname_;
  }
  if (itemname) {
    set_has_itemname();
    itemname_ = itemname;
  } else {
    clear_has_itemname();
    itemname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 itemValue = 3;
inline bool Transaction_MsgItem::has_itemvalue() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Transaction_MsgItem::set_has_itemvalue() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Transaction_MsgItem::clear_has_itemvalue() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Transaction_MsgItem::clear_itemvalue() {
  itemvalue_ = 0;
  clear_has_itemvalue();
}
inline ::google::protobuf::int32 Transaction_MsgItem::itemvalue() const {
  return itemvalue_;
}
inline void Transaction_MsgItem::set_itemvalue(::google::protobuf::int32 value) {
  set_has_itemvalue();
  itemvalue_ = value;
}

// optional .Econix.Transaction.ItemType itemType = 4;
inline bool Transaction_MsgItem::has_itemtype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Transaction_MsgItem::set_has_itemtype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Transaction_MsgItem::clear_has_itemtype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Transaction_MsgItem::clear_itemtype() {
  itemtype_ = 0;
  clear_has_itemtype();
}
inline ::Econix::Transaction_ItemType Transaction_MsgItem::itemtype() const {
  return static_cast< ::Econix::Transaction_ItemType >(itemtype_);
}
inline void Transaction_MsgItem::set_itemtype(::Econix::Transaction_ItemType value) {
  assert(::Econix::Transaction_ItemType_IsValid(value));
  set_has_itemtype();
  itemtype_ = value;
}

// -------------------------------------------------------------------

// Transaction

// required string clientName = 1;
inline bool Transaction::has_clientname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Transaction::set_has_clientname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Transaction::clear_has_clientname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Transaction::clear_clientname() {
  if (clientname_ != &::google::protobuf::internal::kEmptyString) {
    clientname_->clear();
  }
  clear_has_clientname();
}
inline const ::std::string& Transaction::clientname() const {
  return *clientname_;
}
inline void Transaction::set_clientname(const ::std::string& value) {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::kEmptyString) {
    clientname_ = new ::std::string;
  }
  clientname_->assign(value);
}
inline void Transaction::set_clientname(const char* value) {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::kEmptyString) {
    clientname_ = new ::std::string;
  }
  clientname_->assign(value);
}
inline void Transaction::set_clientname(const char* value, size_t size) {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::kEmptyString) {
    clientname_ = new ::std::string;
  }
  clientname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Transaction::mutable_clientname() {
  set_has_clientname();
  if (clientname_ == &::google::protobuf::internal::kEmptyString) {
    clientname_ = new ::std::string;
  }
  return clientname_;
}
inline ::std::string* Transaction::release_clientname() {
  clear_has_clientname();
  if (clientname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = clientname_;
    clientname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Transaction::set_allocated_clientname(::std::string* clientname) {
  if (clientname_ != &::google::protobuf::internal::kEmptyString) {
    delete clientname_;
  }
  if (clientname) {
    set_has_clientname();
    clientname_ = clientname;
  } else {
    clear_has_clientname();
    clientname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 clientId = 2;
inline bool Transaction::has_clientid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Transaction::set_has_clientid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Transaction::clear_has_clientid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Transaction::clear_clientid() {
  clientid_ = 0;
  clear_has_clientid();
}
inline ::google::protobuf::int32 Transaction::clientid() const {
  return clientid_;
}
inline void Transaction::set_clientid(::google::protobuf::int32 value) {
  set_has_clientid();
  clientid_ = value;
}

// optional string description = 3 [default = "NONE"];
inline bool Transaction::has_description() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Transaction::set_has_description() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Transaction::clear_has_description() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Transaction::clear_description() {
  if (description_ != _default_description_) {
    description_->assign(*_default_description_);
  }
  clear_has_description();
}
inline const ::std::string& Transaction::description() const {
  return *description_;
}
inline void Transaction::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == _default_description_) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void Transaction::set_description(const char* value) {
  set_has_description();
  if (description_ == _default_description_) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void Transaction::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == _default_description_) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Transaction::mutable_description() {
  set_has_description();
  if (description_ == _default_description_) {
    description_ = new ::std::string(*_default_description_);
  }
  return description_;
}
inline ::std::string* Transaction::release_description() {
  clear_has_description();
  if (description_ == _default_description_) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(_default_description_);
    return temp;
  }
}
inline void Transaction::set_allocated_description(::std::string* description) {
  if (description_ != _default_description_) {
    delete description_;
  }
  if (description) {
    set_has_description();
    description_ = description;
  } else {
    clear_has_description();
    description_ = const_cast< ::std::string*>(_default_description_);
  }
}

// repeated .Econix.Transaction.MsgItem messageitems = 4;
inline int Transaction::messageitems_size() const {
  return messageitems_.size();
}
inline void Transaction::clear_messageitems() {
  messageitems_.Clear();
}
inline const ::Econix::Transaction_MsgItem& Transaction::messageitems(int index) const {
  return messageitems_.Get(index);
}
inline ::Econix::Transaction_MsgItem* Transaction::mutable_messageitems(int index) {
  return messageitems_.Mutable(index);
}
inline ::Econix::Transaction_MsgItem* Transaction::add_messageitems() {
  return messageitems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Econix::Transaction_MsgItem >&
Transaction::messageitems() const {
  return messageitems_;
}
inline ::google::protobuf::RepeatedPtrField< ::Econix::Transaction_MsgItem >*
Transaction::mutable_messageitems() {
  return &messageitems_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Econix

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Econix::Transaction_ItemType>() {
  return ::Econix::Transaction_ItemType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_a_2eproto__INCLUDED
