// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a.proto

package Econix;

public final class A {
  private A() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransactionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string clientName = 1;
    /**
     * <code>required string clientName = 1;</code>
     */
    boolean hasClientName();
    /**
     * <code>required string clientName = 1;</code>
     */
    java.lang.String getClientName();
    /**
     * <code>required string clientName = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientNameBytes();

    // required int32 clientId = 2;
    /**
     * <code>required int32 clientId = 2;</code>
     */
    boolean hasClientId();
    /**
     * <code>required int32 clientId = 2;</code>
     */
    int getClientId();

    // optional string description = 3 [default = "NONE"];
    /**
     * <code>optional string description = 3 [default = "NONE"];</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 3 [default = "NONE"];</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3 [default = "NONE"];</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // repeated .Econix.Transaction.MsgItem messageitems = 4;
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    java.util.List<Econix.A.Transaction.MsgItem> 
        getMessageitemsList();
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    Econix.A.Transaction.MsgItem getMessageitems(int index);
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    int getMessageitemsCount();
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    java.util.List<? extends Econix.A.Transaction.MsgItemOrBuilder> 
        getMessageitemsOrBuilderList();
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    Econix.A.Transaction.MsgItemOrBuilder getMessageitemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Econix.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage
      implements TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clientName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                messageitems_ = new java.util.ArrayList<Econix.A.Transaction.MsgItem>();
                mutable_bitField0_ |= 0x00000008;
              }
              messageitems_.add(input.readMessage(Econix.A.Transaction.MsgItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          messageitems_ = java.util.Collections.unmodifiableList(messageitems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Econix.A.internal_static_Econix_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Econix.A.internal_static_Econix_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Econix.A.Transaction.class, Econix.A.Transaction.Builder.class);
    }

    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Econix.Transaction.ItemType}
     */
    public enum ItemType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TypeX = 0;</code>
       */
      TypeX(0, 0),
      /**
       * <code>TypeY = 1;</code>
       */
      TypeY(1, 1),
      /**
       * <code>TypeZ = 2;</code>
       */
      TypeZ(2, 2),
      /**
       * <code>TypeA = 3;</code>
       */
      TypeA(3, 3),
      ;

      /**
       * <code>TypeX = 0;</code>
       */
      public static final int TypeX_VALUE = 0;
      /**
       * <code>TypeY = 1;</code>
       */
      public static final int TypeY_VALUE = 1;
      /**
       * <code>TypeZ = 2;</code>
       */
      public static final int TypeZ_VALUE = 2;
      /**
       * <code>TypeA = 3;</code>
       */
      public static final int TypeA_VALUE = 3;


      public final int getNumber() { return value; }

      public static ItemType valueOf(int value) {
        switch (value) {
          case 0: return TypeX;
          case 1: return TypeY;
          case 2: return TypeZ;
          case 3: return TypeA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ItemType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ItemType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ItemType>() {
              public ItemType findValueByNumber(int number) {
                return ItemType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Econix.A.Transaction.getDescriptor().getEnumTypes().get(0);
      }

      private static final ItemType[] VALUES = values();

      public static ItemType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ItemType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Econix.Transaction.ItemType)
    }

    public interface MsgItemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 id = 1;
      /**
       * <code>required int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 1;</code>
       */
      int getId();

      // optional string itemName = 2;
      /**
       * <code>optional string itemName = 2;</code>
       */
      boolean hasItemName();
      /**
       * <code>optional string itemName = 2;</code>
       */
      java.lang.String getItemName();
      /**
       * <code>optional string itemName = 2;</code>
       */
      com.google.protobuf.ByteString
          getItemNameBytes();

      // optional int32 itemValue = 3;
      /**
       * <code>optional int32 itemValue = 3;</code>
       */
      boolean hasItemValue();
      /**
       * <code>optional int32 itemValue = 3;</code>
       */
      int getItemValue();

      // optional .Econix.Transaction.ItemType itemType = 4;
      /**
       * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
       */
      boolean hasItemType();
      /**
       * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
       */
      Econix.A.Transaction.ItemType getItemType();
    }
    /**
     * Protobuf type {@code Econix.Transaction.MsgItem}
     */
    public static final class MsgItem extends
        com.google.protobuf.GeneratedMessage
        implements MsgItemOrBuilder {
      // Use MsgItem.newBuilder() to construct.
      private MsgItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MsgItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MsgItem defaultInstance;
      public static MsgItem getDefaultInstance() {
        return defaultInstance;
      }

      public MsgItem getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MsgItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                itemName_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                itemValue_ = input.readInt32();
                break;
              }
              case 32: {
                int rawValue = input.readEnum();
                Econix.A.Transaction.ItemType value = Econix.A.Transaction.ItemType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                } else {
                  bitField0_ |= 0x00000008;
                  itemType_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Econix.A.internal_static_Econix_Transaction_MsgItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Econix.A.internal_static_Econix_Transaction_MsgItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Econix.A.Transaction.MsgItem.class, Econix.A.Transaction.MsgItem.Builder.class);
      }

      public static com.google.protobuf.Parser<MsgItem> PARSER =
          new com.google.protobuf.AbstractParser<MsgItem>() {
        public MsgItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgItem(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MsgItem> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      // optional string itemName = 2;
      public static final int ITEMNAME_FIELD_NUMBER = 2;
      private java.lang.Object itemName_;
      /**
       * <code>optional string itemName = 2;</code>
       */
      public boolean hasItemName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string itemName = 2;</code>
       */
      public java.lang.String getItemName() {
        java.lang.Object ref = itemName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            itemName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string itemName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getItemNameBytes() {
        java.lang.Object ref = itemName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 itemValue = 3;
      public static final int ITEMVALUE_FIELD_NUMBER = 3;
      private int itemValue_;
      /**
       * <code>optional int32 itemValue = 3;</code>
       */
      public boolean hasItemValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 itemValue = 3;</code>
       */
      public int getItemValue() {
        return itemValue_;
      }

      // optional .Econix.Transaction.ItemType itemType = 4;
      public static final int ITEMTYPE_FIELD_NUMBER = 4;
      private Econix.A.Transaction.ItemType itemType_;
      /**
       * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
       */
      public boolean hasItemType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
       */
      public Econix.A.Transaction.ItemType getItemType() {
        return itemType_;
      }

      private void initFields() {
        id_ = 0;
        itemName_ = "";
        itemValue_ = 0;
        itemType_ = Econix.A.Transaction.ItemType.TypeX;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getItemNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, itemValue_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeEnum(4, itemType_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getItemNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, itemValue_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, itemType_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Econix.A.Transaction.MsgItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Econix.A.Transaction.MsgItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Econix.A.Transaction.MsgItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Econix.A.Transaction.MsgItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Econix.A.Transaction.MsgItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Econix.Transaction.MsgItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements Econix.A.Transaction.MsgItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Econix.A.internal_static_Econix_Transaction_MsgItem_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Econix.A.internal_static_Econix_Transaction_MsgItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Econix.A.Transaction.MsgItem.class, Econix.A.Transaction.MsgItem.Builder.class);
        }

        // Construct using Econix.A.Transaction.MsgItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          itemName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          itemValue_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          itemType_ = Econix.A.Transaction.ItemType.TypeX;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Econix.A.internal_static_Econix_Transaction_MsgItem_descriptor;
        }

        public Econix.A.Transaction.MsgItem getDefaultInstanceForType() {
          return Econix.A.Transaction.MsgItem.getDefaultInstance();
        }

        public Econix.A.Transaction.MsgItem build() {
          Econix.A.Transaction.MsgItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Econix.A.Transaction.MsgItem buildPartial() {
          Econix.A.Transaction.MsgItem result = new Econix.A.Transaction.MsgItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.itemName_ = itemName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.itemValue_ = itemValue_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.itemType_ = itemType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Econix.A.Transaction.MsgItem) {
            return mergeFrom((Econix.A.Transaction.MsgItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Econix.A.Transaction.MsgItem other) {
          if (other == Econix.A.Transaction.MsgItem.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasItemName()) {
            bitField0_ |= 0x00000002;
            itemName_ = other.itemName_;
            onChanged();
          }
          if (other.hasItemValue()) {
            setItemValue(other.getItemValue());
          }
          if (other.hasItemType()) {
            setItemType(other.getItemType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Econix.A.Transaction.MsgItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Econix.A.Transaction.MsgItem) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 id = 1;
        private int id_ ;
        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        // optional string itemName = 2;
        private java.lang.Object itemName_ = "";
        /**
         * <code>optional string itemName = 2;</code>
         */
        public boolean hasItemName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string itemName = 2;</code>
         */
        public java.lang.String getItemName() {
          java.lang.Object ref = itemName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            itemName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string itemName = 2;</code>
         */
        public com.google.protobuf.ByteString
            getItemNameBytes() {
          java.lang.Object ref = itemName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            itemName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string itemName = 2;</code>
         */
        public Builder setItemName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          itemName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string itemName = 2;</code>
         */
        public Builder clearItemName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          itemName_ = getDefaultInstance().getItemName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string itemName = 2;</code>
         */
        public Builder setItemNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          itemName_ = value;
          onChanged();
          return this;
        }

        // optional int32 itemValue = 3;
        private int itemValue_ ;
        /**
         * <code>optional int32 itemValue = 3;</code>
         */
        public boolean hasItemValue() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 itemValue = 3;</code>
         */
        public int getItemValue() {
          return itemValue_;
        }
        /**
         * <code>optional int32 itemValue = 3;</code>
         */
        public Builder setItemValue(int value) {
          bitField0_ |= 0x00000004;
          itemValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 itemValue = 3;</code>
         */
        public Builder clearItemValue() {
          bitField0_ = (bitField0_ & ~0x00000004);
          itemValue_ = 0;
          onChanged();
          return this;
        }

        // optional .Econix.Transaction.ItemType itemType = 4;
        private Econix.A.Transaction.ItemType itemType_ = Econix.A.Transaction.ItemType.TypeX;
        /**
         * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
         */
        public boolean hasItemType() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
         */
        public Econix.A.Transaction.ItemType getItemType() {
          return itemType_;
        }
        /**
         * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
         */
        public Builder setItemType(Econix.A.Transaction.ItemType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          itemType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Econix.Transaction.ItemType itemType = 4;</code>
         */
        public Builder clearItemType() {
          bitField0_ = (bitField0_ & ~0x00000008);
          itemType_ = Econix.A.Transaction.ItemType.TypeX;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Econix.Transaction.MsgItem)
      }

      static {
        defaultInstance = new MsgItem(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Econix.Transaction.MsgItem)
    }

    private int bitField0_;
    // required string clientName = 1;
    public static final int CLIENTNAME_FIELD_NUMBER = 1;
    private java.lang.Object clientName_;
    /**
     * <code>required string clientName = 1;</code>
     */
    public boolean hasClientName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string clientName = 1;</code>
     */
    public java.lang.String getClientName() {
      java.lang.Object ref = clientName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string clientName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      java.lang.Object ref = clientName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 clientId = 2;
    public static final int CLIENTID_FIELD_NUMBER = 2;
    private int clientId_;
    /**
     * <code>required int32 clientId = 2;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 clientId = 2;</code>
     */
    public int getClientId() {
      return clientId_;
    }

    // optional string description = 3 [default = "NONE"];
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 3 [default = "NONE"];</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string description = 3 [default = "NONE"];</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 3 [default = "NONE"];</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Econix.Transaction.MsgItem messageitems = 4;
    public static final int MESSAGEITEMS_FIELD_NUMBER = 4;
    private java.util.List<Econix.A.Transaction.MsgItem> messageitems_;
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    public java.util.List<Econix.A.Transaction.MsgItem> getMessageitemsList() {
      return messageitems_;
    }
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    public java.util.List<? extends Econix.A.Transaction.MsgItemOrBuilder> 
        getMessageitemsOrBuilderList() {
      return messageitems_;
    }
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    public int getMessageitemsCount() {
      return messageitems_.size();
    }
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    public Econix.A.Transaction.MsgItem getMessageitems(int index) {
      return messageitems_.get(index);
    }
    /**
     * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
     */
    public Econix.A.Transaction.MsgItemOrBuilder getMessageitemsOrBuilder(
        int index) {
      return messageitems_.get(index);
    }

    private void initFields() {
      clientName_ = "";
      clientId_ = 0;
      description_ = "NONE";
      messageitems_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClientName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMessageitemsCount(); i++) {
        if (!getMessageitems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClientNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      for (int i = 0; i < messageitems_.size(); i++) {
        output.writeMessage(4, messageitems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      for (int i = 0; i < messageitems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, messageitems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Econix.A.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Econix.A.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Econix.A.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Econix.A.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Econix.A.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Econix.A.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Econix.A.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Econix.A.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Econix.A.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Econix.A.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Econix.A.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Econix.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Econix.A.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Econix.A.internal_static_Econix_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Econix.A.internal_static_Econix_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Econix.A.Transaction.class, Econix.A.Transaction.Builder.class);
      }

      // Construct using Econix.A.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageitemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "NONE";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (messageitemsBuilder_ == null) {
          messageitems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          messageitemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Econix.A.internal_static_Econix_Transaction_descriptor;
      }

      public Econix.A.Transaction getDefaultInstanceForType() {
        return Econix.A.Transaction.getDefaultInstance();
      }

      public Econix.A.Transaction build() {
        Econix.A.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Econix.A.Transaction buildPartial() {
        Econix.A.Transaction result = new Econix.A.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientName_ = clientName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (messageitemsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            messageitems_ = java.util.Collections.unmodifiableList(messageitems_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.messageitems_ = messageitems_;
        } else {
          result.messageitems_ = messageitemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Econix.A.Transaction) {
          return mergeFrom((Econix.A.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Econix.A.Transaction other) {
        if (other == Econix.A.Transaction.getDefaultInstance()) return this;
        if (other.hasClientName()) {
          bitField0_ |= 0x00000001;
          clientName_ = other.clientName_;
          onChanged();
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        if (messageitemsBuilder_ == null) {
          if (!other.messageitems_.isEmpty()) {
            if (messageitems_.isEmpty()) {
              messageitems_ = other.messageitems_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMessageitemsIsMutable();
              messageitems_.addAll(other.messageitems_);
            }
            onChanged();
          }
        } else {
          if (!other.messageitems_.isEmpty()) {
            if (messageitemsBuilder_.isEmpty()) {
              messageitemsBuilder_.dispose();
              messageitemsBuilder_ = null;
              messageitems_ = other.messageitems_;
              bitField0_ = (bitField0_ & ~0x00000008);
              messageitemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageitemsFieldBuilder() : null;
            } else {
              messageitemsBuilder_.addAllMessages(other.messageitems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientName()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        for (int i = 0; i < getMessageitemsCount(); i++) {
          if (!getMessageitems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Econix.A.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Econix.A.Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string clientName = 1;
      private java.lang.Object clientName_ = "";
      /**
       * <code>required string clientName = 1;</code>
       */
      public boolean hasClientName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string clientName = 1;</code>
       */
      public java.lang.String getClientName() {
        java.lang.Object ref = clientName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string clientName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientNameBytes() {
        java.lang.Object ref = clientName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string clientName = 1;</code>
       */
      public Builder setClientName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string clientName = 1;</code>
       */
      public Builder clearClientName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientName_ = getDefaultInstance().getClientName();
        onChanged();
        return this;
      }
      /**
       * <code>required string clientName = 1;</code>
       */
      public Builder setClientNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientName_ = value;
        onChanged();
        return this;
      }

      // required int32 clientId = 2;
      private int clientId_ ;
      /**
       * <code>required int32 clientId = 2;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 clientId = 2;</code>
       */
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>required int32 clientId = 2;</code>
       */
      public Builder setClientId(int value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clientId = 2;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0;
        onChanged();
        return this;
      }

      // optional string description = 3 [default = "NONE"];
      private java.lang.Object description_ = "NONE";
      /**
       * <code>optional string description = 3 [default = "NONE"];</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string description = 3 [default = "NONE"];</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 3 [default = "NONE"];</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 3 [default = "NONE"];</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3 [default = "NONE"];</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3 [default = "NONE"];</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      // repeated .Econix.Transaction.MsgItem messageitems = 4;
      private java.util.List<Econix.A.Transaction.MsgItem> messageitems_ =
        java.util.Collections.emptyList();
      private void ensureMessageitemsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          messageitems_ = new java.util.ArrayList<Econix.A.Transaction.MsgItem>(messageitems_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Econix.A.Transaction.MsgItem, Econix.A.Transaction.MsgItem.Builder, Econix.A.Transaction.MsgItemOrBuilder> messageitemsBuilder_;

      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public java.util.List<Econix.A.Transaction.MsgItem> getMessageitemsList() {
        if (messageitemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messageitems_);
        } else {
          return messageitemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public int getMessageitemsCount() {
        if (messageitemsBuilder_ == null) {
          return messageitems_.size();
        } else {
          return messageitemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Econix.A.Transaction.MsgItem getMessageitems(int index) {
        if (messageitemsBuilder_ == null) {
          return messageitems_.get(index);
        } else {
          return messageitemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder setMessageitems(
          int index, Econix.A.Transaction.MsgItem value) {
        if (messageitemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageitemsIsMutable();
          messageitems_.set(index, value);
          onChanged();
        } else {
          messageitemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder setMessageitems(
          int index, Econix.A.Transaction.MsgItem.Builder builderForValue) {
        if (messageitemsBuilder_ == null) {
          ensureMessageitemsIsMutable();
          messageitems_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageitemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder addMessageitems(Econix.A.Transaction.MsgItem value) {
        if (messageitemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageitemsIsMutable();
          messageitems_.add(value);
          onChanged();
        } else {
          messageitemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder addMessageitems(
          int index, Econix.A.Transaction.MsgItem value) {
        if (messageitemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageitemsIsMutable();
          messageitems_.add(index, value);
          onChanged();
        } else {
          messageitemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder addMessageitems(
          Econix.A.Transaction.MsgItem.Builder builderForValue) {
        if (messageitemsBuilder_ == null) {
          ensureMessageitemsIsMutable();
          messageitems_.add(builderForValue.build());
          onChanged();
        } else {
          messageitemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder addMessageitems(
          int index, Econix.A.Transaction.MsgItem.Builder builderForValue) {
        if (messageitemsBuilder_ == null) {
          ensureMessageitemsIsMutable();
          messageitems_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageitemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder addAllMessageitems(
          java.lang.Iterable<? extends Econix.A.Transaction.MsgItem> values) {
        if (messageitemsBuilder_ == null) {
          ensureMessageitemsIsMutable();
          super.addAll(values, messageitems_);
          onChanged();
        } else {
          messageitemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder clearMessageitems() {
        if (messageitemsBuilder_ == null) {
          messageitems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          messageitemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Builder removeMessageitems(int index) {
        if (messageitemsBuilder_ == null) {
          ensureMessageitemsIsMutable();
          messageitems_.remove(index);
          onChanged();
        } else {
          messageitemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Econix.A.Transaction.MsgItem.Builder getMessageitemsBuilder(
          int index) {
        return getMessageitemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Econix.A.Transaction.MsgItemOrBuilder getMessageitemsOrBuilder(
          int index) {
        if (messageitemsBuilder_ == null) {
          return messageitems_.get(index);  } else {
          return messageitemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public java.util.List<? extends Econix.A.Transaction.MsgItemOrBuilder> 
           getMessageitemsOrBuilderList() {
        if (messageitemsBuilder_ != null) {
          return messageitemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messageitems_);
        }
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Econix.A.Transaction.MsgItem.Builder addMessageitemsBuilder() {
        return getMessageitemsFieldBuilder().addBuilder(
            Econix.A.Transaction.MsgItem.getDefaultInstance());
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public Econix.A.Transaction.MsgItem.Builder addMessageitemsBuilder(
          int index) {
        return getMessageitemsFieldBuilder().addBuilder(
            index, Econix.A.Transaction.MsgItem.getDefaultInstance());
      }
      /**
       * <code>repeated .Econix.Transaction.MsgItem messageitems = 4;</code>
       */
      public java.util.List<Econix.A.Transaction.MsgItem.Builder> 
           getMessageitemsBuilderList() {
        return getMessageitemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Econix.A.Transaction.MsgItem, Econix.A.Transaction.MsgItem.Builder, Econix.A.Transaction.MsgItemOrBuilder> 
          getMessageitemsFieldBuilder() {
        if (messageitemsBuilder_ == null) {
          messageitemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Econix.A.Transaction.MsgItem, Econix.A.Transaction.MsgItem.Builder, Econix.A.Transaction.MsgItemOrBuilder>(
                  messageitems_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          messageitems_ = null;
        }
        return messageitemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Econix.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Econix.Transaction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Econix_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Econix_Transaction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Econix_Transaction_MsgItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Econix_Transaction_MsgItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007a.proto\022\006Econix\"\245\002\n\013Transaction\022\022\n\ncli" +
      "entName\030\001 \002(\t\022\020\n\010clientId\030\002 \002(\005\022\031\n\013descr" +
      "iption\030\003 \001(\t:\004NONE\0221\n\014messageitems\030\004 \003(\013" +
      "2\033.Econix.Transaction.MsgItem\032j\n\007MsgItem" +
      "\022\n\n\002id\030\001 \002(\005\022\020\n\010itemName\030\002 \001(\t\022\021\n\titemVa" +
      "lue\030\003 \001(\005\022.\n\010itemType\030\004 \001(\0162\034.Econix.Tra" +
      "nsaction.ItemType\"6\n\010ItemType\022\t\n\005TypeX\020\000" +
      "\022\t\n\005TypeY\020\001\022\t\n\005TypeZ\020\002\022\t\n\005TypeA\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Econix_Transaction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Econix_Transaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Econix_Transaction_descriptor,
              new java.lang.String[] { "ClientName", "ClientId", "Description", "Messageitems", });
          internal_static_Econix_Transaction_MsgItem_descriptor =
            internal_static_Econix_Transaction_descriptor.getNestedTypes().get(0);
          internal_static_Econix_Transaction_MsgItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Econix_Transaction_MsgItem_descriptor,
              new java.lang.String[] { "Id", "ItemName", "ItemValue", "ItemType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
